### ISSUE TITLE
Remove uses of CF `Unqualified` annotation

### ISSUE THREAD

**Issue by wmdietl** [opprop/checker-framework-inference#1]
CFI uses the `Unqualified` annotation in certain situations, e.g. here:

https://github.com/opprop/checker-framework-inference/blob/master/src/checkers/inference/InferenceAnnotatedTypeFactory.java#L148

All these uses should be removed and the "real" type annotations should be used instead.

**Comment by Ao-senXiong** [comment]
Closed as finished. Open new issue if find new uses of `unqualified` annotation.
