### ISSUE TITLE
Unused context and z3BitVectorCodec field in Z3Solver

### ISSUE THREAD

**Issue by topnessman** [opprop/checker-framework-inference#106]
https://github.com/opprop/checker-framework-inference/blob/168aba4321dd219723bd5b33d31217f84d9a9dbb/src/checkers/inference/solver/backend/z3/Z3Solver.java#L28
https://github.com/opprop/checker-framework-inference/blob/168aba4321dd219723bd5b33d31217f84d9a9dbb/src/checkers/inference/solver/backend/z3/Z3Solver.java#L30
Field `context` and `z3BitVectorCodec` are not used in Z3Solver. Is it better to instantiate `Context` instance and `Z3BitVectorCodec` instance in Z3FormatTranslator and provides a getter method to them? What was the point of having these two fields in `Z3Solver` if they were not used.
If we move them to `Z3FormatTranslator`, we'll not have the issue of creating encoders. due to initialization order no matter we use factory methods or abstract factory pattern.

**Comment by CharlesZ-Chen** [comment]
Hi Mier, thanks for pointing out this! For `z3BitVectorCodec`, it should be removed (originally I used this before introducing `Translator` interface, and it seems I forget to clean up this field after the refactor.) I will remove this field.

Regarding `context`, it actually used in `Z3Solver` to create the underlying solver instance, see:

https://github.com/opprop/checker-framework-inference/blob/168aba4321dd219723bd5b33d31217f84d9a9dbb/src/checkers/inference/solver/backend/z3/Z3Solver.java#L38

since `context` is both used to create the underlying `solver` instance, and used to create encoded variable, constraints, so I need to share this object between `z3Solver` and `z3FormatTranslator`...

Currently I have no better idea on how to avoid the post initialization issue caused by sharing this `context` object....

**Comment by CharlesZ-Chen** [comment]
Maybe as you said, I can move the `context` and `solver` initialization into `z3FormatTranslator`, then provide getter methods to `Z3Solver` for these two objects. The thing is it somehow feeling strange to get a `solver` instance from a `formatTranslator`...

What is your point regarding their (`context` and `solver`) initializations?

**Comment by CharlesZ-Chen** [comment]
The other thing I really don't like on `z3` java API design is, they design `context` as the center coordinator, but it doesn't allow me to get an existed `solver` instance from `context`, which is created by this `context` before. It would be better to provide this getter method, so I can only share `context` except other instances...

**Comment by topnessman** [comment]
We both agree to remove `z3BitVectorCodec` right?
For the `context`, if the way this field is used in `Z3Solver` is only to create `Optimize` instance but no others, I don't think there is point to leave it in Z3Solver. Instead, in `Z3FormatTranslator`, we use `context` instance much more times than in `Z3Solver`, so maybe it's better to initialize `context` instance in `Z3FormatTranslator`?
For the `solver` instance, yes it looks a bit weird to get it from FormatTranslator, so we may provide a getter method to `context` instance, and then instantiate `solver` instance still in `Z3Solver`(keep the existing implementation). 
How does this sound like?

**Comment by topnessman** [comment]
It's a little shocking that `solver` instance will be get out of `context` instance. That doesn't feel intuitive.

**Comment by CharlesZ-Chen** [comment]
>We both agree to remove z3BitVectorCodec right?
Yes.

> we may provide a getter method to context instance, and then instantiate solver instance still in Z3Solver

The issue is then we still need to share this `solver` instance back to the `formatTranslator`... Because `solver` instance is needed for adding customized preference constraints in `formatTranslator`, see:'

https://github.com/opprop/checker-framework-inference/blob/master/src/checkers/inference/solver/backend/z3/Z3BitVectorFormatTranslator.java#L92

**Comment by CharlesZ-Chen** [comment]
> It's a little shocking that solver instance will be get out of context instance. That doesn't feel intuitive.

Well, `context` create everything, to me it seems as the center coordinator, just like `InferenceMain`. It would be much easier to only share the center coordinator, then getting others from it....

**Comment by CharlesZ-Chen** [comment]
P.S. The "customized preference constraints" are not normal `PreferenceConstraint`, is a way of expressing some preference when encoding other constraints, e.g.

When encoding `SubtypeConstraint`, I want to say:

```
if supertype is constant:
  prefer subtype equal to supertype
```

So I need this `solver` instance within `formatTranslator`, to allow me express this additional preference when encoding constraints.

**Comment by topnessman** [comment]
Yeah, I know you need the xxx instance in yyy position, but it doesn't mean it should be the place to instantiate that instance.
What if we even move `solver` instance to `formatTranslator`? I know it may look strange, but the strangeness comes in the first place from when `solver` is needed to add preference constraint(whatever preference constraint definition doesn't matter).

**Comment by topnessman** [comment]
`solver` instance in 'formattranslator' is write access, but in `Z3Solver` all the uses are readonly. Does that indicate `solver` instance should be owned by 'formattranslator' ?

**Comment by CharlesZ-Chen** [comment]
> solver instance in 'formattranslator' is write access, but in Z3Solver all the uses are readonly. Does that indicate solver instance should be owned by 'formattranslator' ?

What do you mean by `write access`?

`solver` in `formatTranslator` only written once (assign the `solver` instance get from `z3Solver` to the `solver` field in `formatTranslator`).

**Comment by topnessman** [comment]
I mean `solver.AssertSoft(constraint, weight, group);` is adding constraints into solver, which is write access.

**Comment by CharlesZ-Chen** [comment]
> but the strangeness comes in the first place from when solver is needed to add preference constraint

Well, it is not strange that we need solver to add soft constraint, as this means we add soft clauses into solver, which need to explicitly add

**Comment by CharlesZ-Chen** [comment]
Ok, I have an idea on avoiding sharing `solver` with `formatTranslator`.

When creating additional soft constraints, `formatTranslator` just store them in a internal set. After `z3Solver` serializing all constraints by `formatTranslator`, it get those additional soft constraints from `formatTranslator` and add into `solver` with `softAssert()`.

Then we can only share `context` between `formatTranslator` and `z3Solver`, and we can move `context` initialization into `formatTranslator`.

**Comment by topnessman** [comment]
Ok, I'm rather confused. Storing the soft constraints in internal set doesn't sound any better than sharing `solver` instance. What if the soft constraints are large?
For me, it looks like moving both `context` and `solver` instance initialization to `formattranslator` doesn't make that much difference, because somehow both need it and no one has a compelling reason to own its initialization than the other one.
If we at least have `context` in `Z3FormatTranslator`, we won't have the initialization of encoders problem, as the Z3XXXEncoder only uses `context` reference, not `solver` instance.

**Comment by CharlesZ-Chen** [comment]
>  because somehow both need it and no one has a compelling reason to own its initialization than the other one.

Generally from architecture view I prefer having them initialized by `z3Solver`, as `z3Solver` is the one responsible for coordinating all the underlying solver adaptation logic, and `formatTranslator` should only responsible for encoding/decoding.

From implementation view, maybe it would be a bit easier to move `context` and `solver` initialization to `formatTranslator`.

**Comment by topnessman** [comment]
I'm not saying we must move them. If you think keeping them in existing places is the right way, then do it. The only thing that need attention is that right inside `initSolver()` method, you need to explicitly call factory(I'll use abstract factory pattern) to set the supported encoders.

**Comment by CharlesZ-Chen** [comment]
>  If you think keeping them in existing places is the right way
Yes, I think `z3Solver` should be  responsible for initializing `context` and `solver` instances.

 > The only thing that need attention is that right inside initSolver() method, you need to explicitly call factory

Sure, I can adapt to your changes.
