### ISSUE TITLE
How to solve the discrepencies between opprop master and pascaliUWat master

### ISSUE THREAD

**Issue by topnessman** [opprop/checker-framework-inference#11]
There are unique commits that have the same changesets but different hash due to some historical problem, for each of the two repositories. So, if I base my slotmanager on pascaliUWat master branch, there are always those unique commits entering my pull request, bringing in duplicate changes. Is the way of solving this merging each other's master branches first? Otherwise, those unique commits always cause duplication changesets in future pull request between opprop and pascaliUWat. @wmdietl

**Comment by wmdietl** [comment]
We discussed this issue in person. The solution is: we'll focus work on opprop, push changes up to typetools, where they might get squished, and then we force update opprop.
People that work on a then out-of-date opprop clone will need to re-base their changes.
