### ISSUE TITLE
Relocate lingeling to CFI/lib

### ISSUE THREAD

**Issue by jyluo** [opprop/checker-framework-inference#215]
Per discussion in https://github.com/opprop/checker-framework-inference/pull/214 it would be good to relocate the installation of lingeling to CF/lib to keep it consistent with z3's installation.

**Comment by xingweitian** [comment]
noted with thanks

**Comment by wmdietl** [comment]
What directory do you mean with `CF/lib`?

**Comment by xingweitian** [comment]
I think it means that we can install lingeling into checker-framework-inference/lib.

**Comment by jyluo** [comment]
Ah yes, I meant CFI/lib

**Comment by xingweitian** [comment]
I found that we exported [LINGELING](https://github.com/opprop/checker-framework-inference/blob/master/testing/dataflowexample/travis-test.sh#L10) as an environment variable in `CIF/testing/dataflowexample/travis-test.sh`.
I was just wondering that whether we can use it to determine the path of Lingeling. I am not sure if it is a good idea since LINGELING is also dependent on JSR308.

**Comment by wmdietl** [comment]
At the moment both lingeling and z3 are set to files in CFI/lib here: https://github.com/opprop/checker-framework-inference/blob/master/build.gradle#L26
But this abuses the `lib` subdirectory as a temporary-solver-installation directory, which isn't particularly nice. Then `.gitignore` needs to ignore that whole directory: https://github.com/opprop/checker-framework-inference/blob/master/.gitignore#L20

Could we think more broadly about a nice solution for how and where to install external solvers? Maybe just a better directory name `external-solvers` with a descriptive `README` file in it will improve things.

**Comment by jyluo** [comment]
The `lingeling.tar.gz` is an archive of its sources, whereas `com.microsoft.z3.jar` is the binaries. The lingeling build script https://github.com/opprop/checker-framework-inference/blob/master/scripts/buildLingeling actually puts the tar in `$JSR308` instead of CFI/lib.

I agree that `lib` should be renamed to `external-solvers`, and should contain only binaries. Lets also have a `external-solvers-setup` as the temporary-solver-installation directory?
