### ISSUE TITLE
Add withExistential() into BaseInferrableChecker?

### ISSUE THREAD

**Issue by topnessman** [opprop/checker-framework-inference#25]
Last term, we discussed that we need to add two boolean flag: existential and viewpoint adaptation, so that we can separately consider them. My idea is to add withExistential() method to BaseInferrableChecker, and by default it returns true, to let the legacy code leave as they were. For type system like GUT, which has viewpoint adaptation, we override it to return false. Do you think it's a good idea? @wmdietl @CharlesZ-Chen

**Comment by wmdietl** [comment]
Hi Mier,
that sounds reasonable. Similarly to `withCombineConstraints` this should be added to the `InferrableChecker` interface. Also, to match singular/plural between the method names would be good, i.e. it should be `withExistentialConstraints`. Or is it `withExistentialVariables`?
