### ISSUE TITLE
checker.jar is not used first in inference

### ISSUE THREAD

**Issue by topnessman** [opprop/checker-framework-inference#32]
In inference, we have a bunch of jar files in dist directory. When we run the inference, those jar files are added to the classpath in the alphabetical order, like annotation-file-utilities.jar is the first to be used.
What's worse is: annotation-file-utilities.jar are created by zipping class files from plume.jar in its own distribution, which is last updated three months ago.
plume.jar in plume-lib directory are zipped from classes in checker-qual-2.1.1.jar in its own distribution, which is last updated one month ago.
The question is: should we remove the class file duplication in the three jar files? Or we work around the problem by setting the classpath correctly in inference?

**Comment by jyluo** [comment]
Closing this issue: from the history of https://github.com/opprop/checker-framework-inference/blob/master/scripts/inference it seems that checker.jar has always appeared first in the classpath.

I'm not convinced that there's a problem given all the tests and scripts work.
