### ISSUE TITLE
Don't use CombVarSlot for LUB representation

### ISSUE THREAD

**Issue by CharlesZ-Chen** [opprop/checker-framework-inference#88]
In `InferenceQualifierHierarchy#leastUpperBound()`, it use `CombVarSlot` for representing a newly created LUB for the given two VarAnnos.

This is improper as `CombVarSlot` is order-sensitive (i.e. a CombVar with receiver `a` and target `b` is different with a CombVar with receiver `b` and target `a`a), while LUB of two VarAnno is order-insensitive (i.e. LUB of `a` and `b` is the same as LUB of `b` and `a`).

Should create a new type of slot, maybe `LUBSlot`, for LUB representation, which internally maintain a set of VarAnnos instead of a list of VarAnnos.

**Comment by jyluo** [comment]
Fixed in https://github.com/opprop/checker-framework-inference/pull/151
