### ISSUE TITLE
Duplicate VectorUtils in CFI

### ISSUE THREAD

**Issue by topnessman** [opprop/checker-framework-inference#94]
One is in checkers.inference.solver.util.VectorUtils
The other is checkers.inference.solver.backend.maxsat.VectorUtils
Please leave only one of the two. Thanks. @CharlesZ-Chen

**Comment by CharlesZ-Chen** [comment]
Ah, seems I forget to delete one when I do the migration. Solved by #97 . I will merge it once it pass travis test.

**Comment by CharlesZ-Chen** [comment]
Solved by #97
